import fs from 'node:fs';
import path from 'node:path';
import { medusa } from './api/client';
import type { ProductListResponse } from './api/types';
import { renderHome } from './pages/home';
import { renderProductDetail } from './pages/product';
import { renderLogin } from './pages/login';
import { renderRegister } from './pages/register';
import { renderAccount } from './pages/account';
import { renderCart } from './pages/cart';
import { renderCheckout } from './pages/checkout';

/**
 * Custom SSG (Static Site Generation) script.
 */
const generateSSG = async () => {
  const DIST_PATH = path.resolve(process.cwd(), 'dist');
  const PRODUCTS_PATH = path.resolve(DIST_PATH, 'products');

  // Load the index.html template generated by Vite
  const templatePath = path.resolve(DIST_PATH, 'index.html');
  if (!fs.existsSync(templatePath)) {
    console.error('Vite build must be completed before running SSG.');
    return;
  }
  const template = fs.readFileSync(templatePath, 'utf-8');

  console.log('--- Starting SSG Process ---');

  // Helper to inject content into template
  const inject = (htmlTemplate: string, content: string, title: string) => {
    return htmlTemplate
      .replace('<div id="app"></div>', `<div id="app">${content}</div>`)
      .replace(/<title>.*?<\/title>/, `<title>${title}</title>`);
  };

  const writePage = (dirPath: string, content: string, title: string) => {
    if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
    fs.writeFileSync(path.resolve(dirPath, 'index.html'), inject(template, content, title));
  };

  try {
    // 1. Core Pages
    const homeData = await renderHome();
    fs.writeFileSync(templatePath, inject(template, homeData.html, homeData.title));
    console.log('✓ Home page prerendered.');

    const pages = [
      { name: 'Login', render: renderLogin, path: 'login' },
      { name: 'Register', render: renderRegister, path: 'register' },
      { name: 'Account', render: renderAccount, path: 'account' },
      { name: 'Cart', render: renderCart, path: 'cart' },
      { name: 'Checkout', render: renderCheckout, path: 'checkout' },
    ];

    for (const page of pages) {
      const data = await page.render();
      writePage(path.resolve(DIST_PATH, page.path), data.html, data.title);
      console.log(`✓ ${page.name} page prerendered.`);
    }

    // 2. Product Detail Pages (PDP)
    const { products } = await medusa.get<ProductListResponse>('/store/products');
    console.log(`Found ${products.length} products to prerender.`);

    if (!fs.existsSync(PRODUCTS_PATH)) fs.mkdirSync(PRODUCTS_PATH, { recursive: true });

    for (const product of products) {
      console.log(`Prerendering: ${product.title} (/products/${product.handle})`);
      const productData = await renderProductDetail({ handle: product.handle });
      writePage(path.resolve(PRODUCTS_PATH, product.handle), productData.html, productData.title);
    }

    console.log('--- SSG Completed successfully! ---');
  } catch (error) {
    console.error('Error during SSG generation:', error);
    process.exit(1);
  }
};

// Execution
generateSSG();
